#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_hash=$(git rev-parse HEAD)
commit_message=$(git log -1 --pretty=%B)
commit_author_name=$(git log -1 --pretty=%an)
commit_author_email=$(git log -1 --pretty=%ae)
commit_date=$(git log -1 --pretty=%ci)

cd project-example
node sendCommitData "$commit_hash" "$commit_message" "$commit_author_name" "$commit_author_email" "$commit_date"