#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_hash=$(git rev-parse HEAD)
commit_message=$(git log -1 --pretty=%B)

cd project-example
node sendCommitData "$commit_hash" "$commit_message"